### PR TITLE
Improved file3

### PR DESCRIPTION
**Pull request by bradboyle**
Check out this devastatingly good enhancement of file3.

### CODE REVIEW

**Comment by ojalaquellueva** [comment]
I suggest changing "really" to "extremely". Make that change and I will accept the change.

**Comment by bradboyle** [comment]
Change is complete

**Comment by ojalaquellueva** [comment]
## Still to be done
- [X] Write the code
- [ ] Write all the tests
- [ ] Document the code

**Comment by ojalaquellueva** [comment]
Code snippet example:

```java
for(int i=0 ; i < 5 ; i++)
{
System.out.println("i is : " + i);
}
```

**Pull request merged**
